# Requesting for letsencrypt cert
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  #Acme server url
    email: ugochiukaegbu21@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod        #Name of secret used to store the ACME account private key
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx 


# Ingress controller routing request to the front-end service 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Qr-app-ingress
  namespace: qr-app
  labels:
    app: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: qr.sapphireaura.com.ng
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: front-end
            port:
              number: 80
  tls:
  - hosts:
      - qr.sapphireaura.com.ng
    secretName: letsencrypt-production
    