# Deployment script for the frontend side of the application

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: qr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      app: Qr-app
  template:
    metadata:
      labels:
        type: frontend
        app: Qr-app
    spec:
      containers:
        - name: frontend
          image: zenitugo/frontend:latest
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
          - containerPort: 3000
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   initialDelaySeconds: 300
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 3
          #   timeoutSeconds: 2
          #   failureThreshold: 3
          #   successThreshold: 1
      

# Service for the front end
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: qr-app
  labels:
    app: Qr-app
    type: frontend
spec:
  type: NodePort
  selector:
    app: Qr-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30500
      