variable "cidr_block" {}
variable "public-subnets" {}
variable "private-subnets" {}
variable "key_name" {}
variable "qrcode-sg" {}
variable "cluster-rolename" {}
variable "node-rolename" {}
variable "csi_role_name" {}
variable "controller_rolename" {}
variable "controller_policyname" {}
variable "cluster" {}
variable "nodegroup" {}
variable "instance-type" {}
variable "key_filepath" {}
variable "addon_name" {}
variable "region" {}
variable "instance-profile" {}