variable "cidr_block" {}
variable "public-subnets" {}
variable "private-subnets" {}
variable "key_name" {}
variable "qrcode-sg" {}
variable "cluster-rolename" {}
variable "node-rolename" {}
variable "role_name" {}
variable "openid-url" {}
variable "openid-arn" {}
variable "controller_rolename" {}
variable "controller_policyname" {}
variable "cluster" {}
variable "eks-clusterrole" {}
variable "private-subnet-ids" {}
variable "nodegroup" {}
variable "noderole" {}
variable "eks-sg" {}
variable "instance-type" {}
variable "key_name" {}
variable "cluster-policy" {}
variable "WorkerPolicy" {}
variable "CNIPolicy" {}
variable "ContainerRegistry" {}
variable "public-subnet-ids" {}
variable "key-id" {}
variable "addon_name" {}
variable "ebs-csi-role" {}
variable "region" {}
variable "bucket-name" {}
variable "dynamodb_table" {}